package IntroAsociacionEntreClases;

public class Introduccion {

	//POR NORMA GENERAL CADA TABLA EN NUESTRA BBDD VA A REPRESENTAR Y UNA CLASE/OBJETO EN NUESTRA APLICACION.
	
	
	//TEMOS 3 TIPOS DE RELACIONES DE CLASES:
	
	// ASOCIACION: ES LA RELACION ENTRE OBJETOS DE CLASES DINTINTAS. PARA HACER ESTO SE SIGUE EL MISMO PROCESO Y EL MISMO ESQUEMA QUE EL MODELO ENTIDAD RELACION QUE UTILIZACION EN BASES DE DATOS.(LA ASOCIACION SE HACE DE FORMA 1:N)
	// AGREGACION/COMPOSICION: UNA AGREGACION DE OBJETOS AL OBJETO. LA EGREGACION SE PINTA CON UN ROMBO EN BLANCO Y LA COMPOSICION CON UN ROMBO EN COLOR. 
	// HERENCIA: CLASE QUE SE ESPECIALIZA.
	
	// LOS OBJETOS SE METEN EN UN PAQUETE QUE SE LLAMA JAVABEANS (OBJETOS)
	
	
	
	
}
