package repaso;

public class RepasoHastaAhora {

	
	/* LO QUE HEMOS VISTO DE LA RELACIONES ENTRE CLASES ES :
	 * ASOCIACION : RELACIONES ENTRE OBJETOS DE DIFERENTES CLASES.ESTA PUEDE DES UNIDIRECCIONAL O BIDIRECCIONAL.
	 * AGREGACION/COMPOSICION : RELACION DE UN TODO A SUS PARTES. LA MIGRACION SIEMPRE VA DE LAS PARTES AL TODO.
	 * LA AGREGACION TIENE UN CASO ESPECIAL EN EL QUE TIENE MUCHOS OBJETOS EN EL QUE CREAMOS UN INTERFACE Y COMO NO TENEMOS BBDD, CREAMOS UNA <LISTA> CON UN MONTON DE OBJTOS Y LO METEMOS EN ESTE INTERFACE.
	 */
	
	//EMPEZAMOS CON LA HERENCIA.
	/* HERENCIA POR ESPECIALIZACION: CAPACIDAD DE UNA CLASE DE HEREDAR ATRIBUTOS Y METODOS DE UNA CLASE "PADRE" O "SUPERCLASE" Y DE UTILIZAR ESTOS ATRIBUTOS Y ADAPTARLOS A LAS NECESIDADES ESPECIFICAS DE LA CLASE "HIJA". LO QUE CON SEGUIMOS CON ESTE TIPO DE HERENCIA ES CREAR UNA NUEVA CLASE QUE ES UNA VERSION ESPECIALIZADA DE OTRA YA EXISTENTE.
	 * PARA HEREDAR USAMOS LA PALABRA "EXTENDS"
	 * 
	 * PARA APPLICAR LA HERENCIA ES IMPORTANTE QUE LOS DATOS SEAN PROTECTED
	 * */
}
