package Automovil;
//LA CLASES ENUMERADOR ES MUY PARECIDO A LAS CLASES NORMALES PERO CONTIENEN VALORES CONSTANTES PARA TRABAJA CON ELLOS
//CONJUNTO DE ATRIBUTOS O VALORES CONSTANTES
public enum Color {
	ROJO,
	AMARILLO,
	AZUL,
	BLANCO,
	GRIS,
	NAANJA
}
