package introduccion;

public class Notas {

	// EMPEZAMOS CON LAS COLLECCIONES:
	/*TENEMOS LIST (COMO EL ARRAY), SET, MAP. TODOS SON DE INTERFACES CON CLASES UTILES
	 * 
	 * LAS LISTAS SOLO TIENEN UN TIPO DE DATO Y ADMINTEN REPETIDOS 
	 * */
	
	
	
}
